---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# mizerShiny

The goal of mizerShiny is to provide a frontend for running [mizer](https://sizespectrum.org/mizer/) models, so that a wider range of people can analyse mizer outputs. It intends to remove the barrier of knowledge and allow individuals to investigate and understand ecosystem-wide trophic interactions. Furthermore, it intends to allow users to balance yield, sustainability and nutrition across different fishery strategies. 

## Running mizerShiny

You can install mizerShiny and then run the default North Sea mizer model like so

```{r example, eval=F}
devtools::install_github("gustavdelius/mizerShiny")
library(mizerShiny)
mizerShiny()
```

To run it with your own mizer model contained in a MizerParams object, pass that as the first argument.

## Tutorial

Click the `Page Guide` button on the top right to get a basic explanation of the current page when in the app. Detailed information can be found in the [User-Guide](doc/User-Guide.pdf) vignette. 

Generally for each page, change the model on the left configuration panel and then analyse the ecosystem impacts on the right. 

## Funding
 
The funding for this project was provided by the Sustainable Management of UK Marine Resources (SMMR) programme, which is jointly administered by the Natural Environment Research Council (NERC) and the Economic and Social Research Council (ESRC).
 
Grant numbers are NE/V017039/1 (Cefas) and NE/V01708X/1 (University of York).
