library(shinytest2)

test_that("{shinytest2} recording: app", {
  app <- AppDriver$new(variant = platform_variant(), name = "app", height = 1198, 
      width = 2098)
  app$set_inputs(`fishery-effort_Pelagic` = 1.4)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(`fishery-effort2_Otter` = 0.2)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(`fishery-species_order_fish` = "Size")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Yield Composition")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Size")
  app$set_inputs(`fishery-logToggle4` = FALSE)
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Guild")
  app$set_inputs(`fishery-triguildToggleFish` = FALSE)
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Spectra")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Diet")
  app$set_inputs(`fishery-fish_name_select` = "Whiting")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Nutrition")
  app$expect_screenshot()
  app$set_inputs(bigtabpanel = "Species Role")
  app$set_window_size(width = 2098, height = 1198)
  app$set_inputs(`species-species` = 46)
  app$set_inputs(`species-mortspecies` = -13)
  app$expect_values()
  app$expect_screenshot()
  app$click("species-incYear_bio")
  app$click("species-incYear_bio")
  app$click("species-incYear_bio")
  app$expect_screenshot()
  app$set_inputs(`species-species_order_bio` = "Size")
  app$set_inputs(`species-triplotToggle` = FALSE)
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Size")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Guilds")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Diet")
  app$set_inputs(`species-diet_species_select` = "Whiting")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Biomass")
  app$set_inputs(`species-year` = 11)
  app$expect_screenshot()
})
