library(shinytest2)

test_that("{shinytest2} recording: app", {
  app <- AppDriver$new(variant = platform_variant(), name = "app", height = 959, 
      width = 1619)
  app$set_inputs(`fishery-effort_Beam` = 0.7)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(`fishery-triplotToggleFish` = FALSE)
  app$set_inputs(`fishery-species_order_fish` = "Size")
  app$expect_screenshot()
  app$click("fishery-customOrderInfo_fish")
  app$click("save_custom_order_fish")
  app$click("save_custom_order_fish")
  app$expect_screenshot()
  app$set_inputs(`fishery-effort2_Pelagic` = 1.4)
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Yield Composition")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Size")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Guild")
  app$set_inputs(`fishery-triguildToggleFish` = FALSE)
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Spectra")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Diet")
  app$set_inputs(`fishery-fish_name_select` = "Gurnard")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Nutrition")
  app$set_inputs(`fishery-sim_choice` = "sim2")
  app$expect_screenshot()
  app$set_inputs(`fishery-fishy_plots` = "Biomass")
  app$set_inputs(`fishery-fishyear` = 7)
  app$expect_screenshot()
  app$click("fishery-incYear_fish")
  app$expect_values()
  app$set_inputs(bigtabpanel = "Species Role")
  app$set_window_size(width = 1619, height = 959)
  app$set_inputs(`species-mortspecies` = 10)
  app$set_inputs(`species-species` = -42)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(`species-species_order_bio` = "Size")
  app$set_inputs(`species-species_order_bio` = "Custom")
  app$set_inputs(`species-species_order_bio` = "Size")
  app$set_inputs(`species-triplotToggle` = FALSE)
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Size")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Guilds")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Diet")
  app$set_inputs(`species-diet_species_select` = "Haddock")
  app$expect_screenshot()
  app$set_inputs(`species-plotTabs` = "Biomass")
  app$click("species-incYear_bio")
  app$click("species-incYear_bio")
  app$expect_values()
  app$expect_screenshot()
})
